
name: BlazeDemo Performance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build JMeter Docker Image
      run: docker build -t blazedemo-performance-test .

    - name: Run JMeter Tests
      run: docker run -v ${{ github.workspace }}:/mnt/jmeter blazedemo-performance-test

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results.jtl

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-report
        path: reports
