name: BlazeDemo Performance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Remove Docker Cache
      run: docker builder prune -f

    - name: Build JMeter Docker Image
      run: docker build -t blazedemo-performance-test .

    - name: Run JMeter Tests
      run: docker run -v ${{ github.workspace }}/results:/results blazedemo-performance-test

    - name: List Results Directory
      run: ls -R /results

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results/results.csv

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-report
        path: results/html-reports
